# Changes here will be overwritten by Copier
_commit: v1.1.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: delucchi@andrew.cmu.edu
author_name: LINCC-Frameworks
create_example_module: false
module_name: hipscat_import
preferred_linter: pylint
project_name: hipscat-import
use_isort: true
